server:
  port: 8840
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.70.132/wzsys?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20


mybatis:
  type-aliases-package: com.com.aweika.mjlyx.api.entity
  mapper-locations: classpath:/mapper/*
  configuration:
    mapUnderscoreToCamelCase: true


mytest:
  name: 方启哲
  age: 18